// data.js
// Fuente de datos del Campus de Ascensos.
//
// Todo es local y estático: no hay conexión a ningún backend. Para agregar
// o modificar marcas, regionales, zonales o locales, se edita directamente
// este archivo.
//
// Forma del organigrama de cada marca (4 niveles, tal como viene el
// organigrama oficial en PDF):
//
//   organigrama.comercial            -> GTE Comercial (uno solo, tope de la marca)
//     .asistente                     -> opcional: par del comercial (ej. Responsable
//                                        Performance Delivery). null/omitido si no tiene.
//   organigrama.regionales[]         -> GTE Regional
//     .asistente                     -> opcional: Asistente de Operaciones del regional.
//                                        null si ese regional no tiene asistente propio.
//     .zonales[]                     -> GTE Zonal (reporta al regional)
//       .locales[]                   -> nombres de los locales a cargo de ese zonal

const ASCENSOS_DATA = {
  brands: [
    {
      id: "hex",
      name: "Hamburguesas Extremas",
      shortCode: "EXT",
      color: "#e02424",
      logoBg: "#fde2e1",
      logoText: "#e02424",
      manager: {
        name: "Evangelina Rodriguez",
        role: "GTE Comercial",
        phone: "11 3611 8446",
        email: "evangelina.rodriguez@extremas.com.ar",
      },
      // Organigrama Hamburguesas Extremas (fuente: PDF provisto por el usuario).
      organigrama: {
        comercial: {
          name: "Evangelina Rodriguez",
          role: "GTE Comercial",
          phone: "11 3611 8446",
          email: "evangelina.rodriguez@extremas.com.ar",
          asistente: {
            name: "Yohanna Masucci",
            role: "Responsable Performance Delivery",
            phone: "11 2630 3924",
            email: "yohanna.masucci@extremas.com.ar",
          },
        },
        regionales: [
          {
            id: "facundo-aramburo",
            name: "Facundo Aramburo",
            role: "GTE Regional",
            phone: "11 2808 0455",
            email: "facundo.aramburo@extremas.com.ar",
            asistente: null,
            zonales: [
              {
                id: "adriana-ibarra",
                name: "Adriana Ibarra",
                role: "GTE Zonal",
                phone: "11 2682 4698",
                email: "adriana.ibarra@extremas.com.ar",
                locales: ["Avellaneda", "Wilde", "Pompeya", "Rosario", "Quilmes"],
              },
              {
                id: "yamila-lugo",
                name: "Yamila Lugo",
                role: "GTE Zonal",
                phone: "11 3927 9756",
                email: "yamila.lugo@extremas.com.ar",
                locales: ["Monte Grande", "Lomas de Zamora", "Banfield", "La Plata", "Berazategui"],
              },
              {
                id: "marianela-mazzeo",
                name: "Marianela Mazzeo",
                role: "GTE Zonal",
                phone: "11 5422 5628",
                email: "marianela.mazzeo@extremas.com.ar",
                locales: ["Solano", "Varela", "Glew", "Temperley", "Lanus", "Adrogué"],
              },
              {
                id: "mayra-agmatt",
                name: "Mayra Agmatt",
                role: "GTE Zonal",
                phone: "11 3301 9204",
                email: "mayra.agmatt@extremas.com.ar",
                locales: ["Florida", "Tucuman", "Once", "Callao", "Pueyrredon", "Pellegrini"],
              },
            ],
          },
          {
            id: "federico-gomez",
            name: "Federico Gomez",
            role: "GTE Regional",
            phone: "11 2159 8392",
            email: "federico.gomez@extremas.com.ar",
            asistente: null,
            zonales: [
              {
                id: "mariano-artigue",
                name: "Mariano Artigue",
                role: "GTE Zonal",
                phone: "11 5006 2830",
                email: "mariano.artigue@extremas.com.ar",
                locales: ["Castelar", "Merlo", "Ramos", "Moreno", "El Palomar"],
              },
              {
                id: "fernando-buosi",
                name: "Fernando Buosi",
                role: "GTE Zonal",
                phone: "11 2792 6162",
                email: "fernando.buosi@extremas.com.ar",
                locales: ["Rodriguez", "Lujan", "Zarate", "Garin"],
              },
              {
                id: "facundo-gimenez",
                name: "Facundo Gimenez",
                role: "GTE Zonal",
                phone: "11 3868 6567",
                email: "facundo.gimenez@extremas.com.ar",
                locales: ["Laferrere", "Moron", "Crovara", "San Justo"],
              },
              {
                id: "juan-pereyra",
                name: "Juan Pereyra",
                role: "GTE Zonal",
                phone: "11 7618 2436",
                email: "juan.pereyra@extremas.com.ar",
                locales: ["Polvorines", "Tortuguitas", "Pilar", "Alberti"],
              },
              {
                id: "jaquelina-polo",
                name: "Jaquelina Polo",
                role: "GTE Zonal",
                phone: "11 3157 3072",
                email: "jaquelina.polo@extremas.com.ar",
                locales: ["Jose C. Paz", "San Miguel", "Grand Bourg", "Talar"],
              },
            ],
          },
          {
            id: "gustavo-gomez",
            name: "Gustavo Gomez",
            role: "GTE Regional",
            phone: "11 2792 0774",
            email: "gustavo.gomez@extremas.com.ar",
            asistente: null,
            zonales: [
              {
                id: "monica-batista",
                name: "Monica Batista",
                role: "GTE Zonal",
                phone: "11 3302 1967",
                email: "monica.batista@extremas.com.ar",
                locales: ["Caballito", "Liniers", "Flores", "Flores 2", "Mataderos"],
              },
              {
                id: "salome-rodriguez",
                name: "Salome Rodriguez",
                role: "GTE Zonal",
                phone: "11 3361 2557",
                email: "salome.rodriguez@extremas.com.ar",
                locales: ["Loma Hermosa", "Hurlingham", "Caseros", "Munro", "José L. Suarez"],
              },
              {
                id: "roxana-gorosito",
                name: "Roxana Gorosito",
                role: "GTE Zonal",
                phone: "11 2792 8390",
                email: "roxana.gorosito@extremas.com.ar",
                locales: ["Olivos", "San Isidro", "Boulogne", "Villa Adelina", "Villa Ballester"],
              },
              {
                id: "lautaro-tesi",
                name: "Lautaro Tesi",
                role: "GTE Zonal",
                phone: "11 2630 2878",
                email: "lautaro.tesi@extremas.com.ar",
                locales: ["San Fernando", "Virreyes", "Pacheco", "Vicente Lopez"],
              },
            ],
          },
        ],
      },
    },
    {
      id: "sabores",
      name: "Sabores Express",
      shortCode: "SBX",
      color: "#1d4ed8",
      logoBg: "#dbeafe",
      logoText: "#1d4ed8",
      manager: {
        name: "Mauro Dalla Valle",
        role: "GTE Comercial",
        phone: "11 2257 5088",
        email: "mauro.dallavalle@saboresexpress.com.ar",
      },
      // Organigrama Sabores Express 2026 (fuente: PDF provisto por el usuario).
      organigrama: {
        comercial: {
          name: "Mauro Dalla Valle",
          role: "GTE Comercial",
          phone: "11 2257 5088",
          email: "mauro.dallavalle@saboresexpress.com.ar",
        },
        regionales: [
          {
            id: "ivo-pisaniello",
            name: "Ivo Pisaniello",
            role: "GTE Regional",
            phone: "2494 24 5315",
            email: "ivo.pisaniello@saboresexpress.com.ar",
            asistente: {
              name: "Isabel Leal",
              role: "Asistente de Operaciones",
              phone: "11 6374 9157",
              email: "isabel.leal@saboresexpress.com.ar",
            },
            zonales: [
              {
                id: "tomas-moreno",
                name: "Tomas Moreno",
                role: "GTE Zonal",
                phone: "11 2537 3963",
                email: "tomas.moreno@saboresexpress.com.ar",
                locales: ["Chilavert", "Caballito 1", "Lomas de Zamora 3", "Lomas de Zamora 4", "Lomas de Zamora 5"],
              },
              {
                id: "greisnell-mejias",
                name: "Greisnell Mejias",
                role: "GTE Zonal",
                phone: "11 2729 2158",
                email: "greisnell.mejias@saboresexpress.com.ar",
                locales: ["Santa Fe 1", "Villa Urquiza", "Entre Rios", "Boedo", "Pellegrini", "Villa del Parque"],
              },
              {
                id: "lesley-duarte",
                name: "Lesley Duarte",
                role: "GTE Zonal (entrenando)",
                phone: null,
                email: "lesley.duarte@saboresexpress.com.ar",
                locales: ["Liniers 1", "Liniers 2", "Ciudadela", "Pompeya"],
              },
              {
                id: "ezequiel-acosta",
                name: "Ezequiel Acosta",
                role: "GTE Zonal",
                phone: "11 2824 4248",
                email: "ezequiel.acosta@saboresexpress.com.ar",
                locales: ["Caballito 2", "Barracas", "Pueyrredon 1", "Pueyrredon 2", "Constitucion", "Flores"],
              },
              {
                id: "douglas-seprum",
                name: "Douglas Seprum",
                role: "GTE Zonal",
                phone: "11 5601 3213",
                email: "douglas.seprum@saboresexpress.com.ar",
                locales: ["Belgrano", "Lavalle 1", "Lavalle 2", "Tucuman", "Florida", "Retiro"],
              },
            ],
          },
          {
            id: "gustavo-cabrera",
            name: "Gustavo Cabrera",
            role: "GTE Regional",
            phone: "11 3230 8121",
            email: "gustavo.cabrera@saboresexpress.com.ar",
            asistente: {
              name: "Gabriel Rios",
              role: "Asistente de Operaciones",
              phone: "11 2323 2060",
              email: "gabriel.rios@saboresexpress.com.ar",
            },
            zonales: [
              {
                id: "marianella-yniguez",
                name: "Marianella Yñiguez",
                role: "GTE Zonal",
                phone: "11 3639 6883",
                email: "marianella.yniguez@saboresexpress.com.ar",
                locales: ["Jose C Paz 1", "Jose C Paz 2", "Del Viso", "Grand Bourg", "Don Torcuato"],
              },
              {
                id: "camila-fredes",
                name: "Camila Fredes",
                role: "GTE Zonal",
                phone: "11 3896 5385",
                email: "camila.fredes@saboresexpress.com.ar",
                locales: ["Santos Lugares", "Bella Vista", "William Morris", "Cruce Castelar", "Loma Hermosa"],
              },
              {
                id: "pamela-maidana",
                name: "Pamela Maidana",
                role: "GTE Zonal",
                phone: "11 2236 6756",
                email: "pamela.maidana@saboresexpress.com.ar",
                locales: ["Hurlingham 1", "Hurlingham 2", "Caseros 1", "Caseros 2", "El Palomar"],
              },
              {
                id: "melanie-pueblas",
                name: "Melanie Pueblas",
                role: "GTE Zonal",
                phone: "11 2536-5726",
                email: "melanie.pueblas@saboresexpress.com.ar",
                locales: ["Manuel Alberti", "Sourdeaux", "Tortuguitas", "Los Polvorines"],
              },
              {
                id: "cecilia-montoya",
                name: "Cecilia Montoya",
                role: "GTE Zonal",
                phone: "11 3256 2305",
                email: "cecilia.montoya@saboresexpress.com.ar",
                locales: ["San Miguel 1", "San Miguel 2", "San Miguel 3", "Pilar 1", "Pilar 2"],
              },
              {
                id: "pamela-gimenez",
                name: "Pamela Gimenez",
                role: "GTE Zonal",
                phone: "11 3203-0406",
                email: "pamela.gimenez@saboresexpress.com.ar",
                locales: ["Crovara", "Tapiales", "Laferrere 1", "Laferrere 2", "Gonzalez Catan"],
              },
            ],
          },
          {
            id: "agustin-sbampato",
            name: "Agustin Sbampato",
            role: "GTE Regional",
            phone: "11 4039 3729",
            email: "agustin.sbampato@saboresexpress.com.ar",
            asistente: {
              name: "Natalia Giorgi",
              role: "Asistente de Operaciones",
              phone: "11 3913 8211",
              email: "natalia.giorgi@saboresexpress.com.ar",
            },
            zonales: [
              {
                id: "franco-pedrazza",
                name: "Franco Pedrazza",
                role: "GTE Zonal",
                phone: "11 5051 7407",
                email: "franco.pedrazza@saboresexpress.com.ar",
                locales: ["La Plata 1", "La Plata 2", "La Plata 3", "La Plata 4", "Lezama"],
              },
              {
                id: "magali-sandoval",
                name: "Magali Sandoval",
                role: "GTE Zonal",
                phone: "11 5574 5202",
                email: "magali.sandoval@saboresexpress.com.ar",
                locales: ["Berazategui 1", "Berazategui 2", "Solano", "Varela", "Cruce Varela", "Varela 2"],
              },
              {
                id: "lujan-brandan",
                name: "Lujan Brandan",
                role: "GTE Zonal",
                phone: "11 3595 7843",
                email: "lujan.brandan@saboresexpress.com.ar",
                locales: ["Mar del Plata 1", "Mar del Plata 2", "Mar del Plata 3", "Mar del Plata 4", "Mar del Plata 5"],
              },
              {
                id: "adriana-alvarez",
                name: "Adriana Alvarez",
                role: "GTE Zonal",
                phone: "11 2286 3972",
                email: "adriana.alvarez@saboresexpress.com.ar",
                locales: ["Adrogue", "Banfield", "Temperley 1", "Temperley 2", "Lanus 2", "Lanus 3"],
              },
              {
                id: "camila-carranza",
                name: "Camila Carranza",
                role: "GTE Zonal",
                phone: "11 4528 5187",
                email: "camila.carranza@saboresexpress.com.ar",
                locales: ["Claypole", "Quilmes 1", "Quilmes 2", "Quilmes 3", "Wilde", "Gerli"],
              },
              {
                id: "michelle-alvarez",
                name: "Michelle Alvarez",
                role: "GTE Zonal",
                phone: "11 2192 4072",
                email: "michelle.alvarez@saboresexpress.com.ar",
                locales: ["El Jaguel", "Monte Grande 1", "Monte Grande 2", "Tristan Suarez", "Glew", "Ezeiza"],
              },
              {
                id: "tamara-migoya",
                name: "Tamara Migoya",
                role: "GTE Zonal",
                phone: "11 3945-9178",
                email: "tamara.migoya@saboresexpress.com.ar",
                locales: ["Ciudadela (Mania)", "Isidro Casanova (Mania)", "Lanus 4", "Valentina Alsina", "Burzaco"],
              },
            ],
          },
          {
            id: "marcelo-biurra",
            name: "Marcelo Biurra",
            role: "GTE Regional",
            phone: "11 2807 0969",
            email: "marcelo.biurra@saboresexpress.com.ar",
            asistente: {
              name: "Ezequiel Albornoz",
              role: "Asistente de Operaciones",
              phone: "11 5621 6850",
              email: "ezequiel.albornoz@saboresexpress.com.ar",
            },
            zonales: [
              {
                id: "ronaldo-arguello",
                name: "Ronaldo Arguello",
                role: "GTE Zonal",
                phone: "11 2696 0273",
                email: "ronaldo.arguello@saboresexpress.com.ar",
                locales: ["Zarate", "Escobar 1", "Maschwitz", "Boulogne", "Benavidez", "Escobar 2"],
              },
              {
                id: "camila-almeida",
                name: "Camila Almeida",
                role: "GTE Zonal",
                phone: "11 3586 2181",
                email: "camila.almeida@saboresexpress.com.ar",
                locales: ["San Fernando", "San Isidro 1", "San Isidro 2", "Virreyes", "Tigre", "Pacheco 2"],
              },
              {
                id: "veronica-gonzalez",
                name: "Veronica Gonzalez",
                role: "GTE Zonal",
                phone: "11 5315 1419",
                email: "veronica.gonzalez@saboresexpress.com.ar",
                locales: ["Pte Saavedra", "Vicente Lopez", "Munro", "Villa Adelina", "Jose Leon Suarez", "Martinez"],
              },
              {
                id: "aylen-ponce",
                name: "Aylen Ponce",
                role: "GTE Zonal",
                phone: "11 2834 4760",
                email: "aylen.ponce@saboresexpress.com.ar",
                locales: ["Pacheco 1", "El Talar", "Olivos", "Garin", "Savio"],
              },
              {
                id: "micaela-ponce",
                name: "Micaela Ponce",
                role: "GTE Zonal",
                phone: "11 2881 4811",
                email: "micaela.ponce@saboresexpress.com.ar",
                locales: ["San Martin 1", "San Martin 2", "Villa Ballester 1", "Villa Ballester 2"],
              },
              {
                id: "giovanna-solerez",
                name: "Giovanna Solerez",
                role: "GTE Zonal",
                phone: "11 2861-1873",
                email: "giovanna.solerez@saboresexpress.com.ar",
                locales: ["Rosario 1", "Rosario 2", "Rosario 3", "San Nicolas"],
              },
            ],
          },
          {
            id: "lucia-velez",
            name: "Lucia Velez",
            role: "GTE Regional",
            phone: "11 2317 2615",
            email: "lucia.velez@saboresexpress.com.ar",
            asistente: {
              name: "Emanuel Mazueco",
              role: "Asistente de Operaciones",
              phone: "11 4166 0463",
              email: "emanuel.mazueco@saboresexpress.com.ar",
            },
            zonales: [
              {
                id: "renata-fedullo",
                name: "Renata Fedullo",
                role: "GTE Zonal",
                phone: "11 5039 8539",
                email: "renata.fedullo@saboresexpress.com.ar",
                locales: ["Ramos Mejia 1", "Ramos Mejia 2", "Ramos Mejia 3", "Haedo", "Ituzaingo"],
              },
              {
                id: "pablo-muga",
                name: "Pablo Muga",
                role: "GTE Zonal",
                phone: "11 7628 4782",
                email: "pablo.muga@saboresexpress.com.ar",
                locales: ["Moron 1", "Moron 2", "Moron 3", "Moron 4", "Moron 5"],
              },
              {
                id: "nahuel-sanchez",
                name: "Nahuel Sanchez",
                role: "GTE Zonal",
                phone: "11 6704 8185",
                email: "nahuel.sanchez@saboresexpress.com.ar",
                locales: ["Lujan", "General Rodriguez", "Moreno 1", "Moreno 2", "Paso del Rey"],
              },
              {
                id: "malena-aguera",
                name: "Malena Aguera",
                role: "GTE Zonal",
                phone: "11 2281 9980",
                email: "malena.aguera@saboresexpress.com.ar",
                locales: ["Merlo 1", "Merlo 2", "Merlo 3", "Rafael Castillo", "Padua"],
              },
              {
                id: "ariana-gomez",
                name: "Ariana Gomez",
                role: "GTE Zonal",
                phone: "11 3703 5062",
                email: "ariana.gomez@saboresexpress.com.ar",
                locales: ["Corrientes 1", "Corrientes 2", "Corrientes 3", "Corrientes 4"],
              },
              {
                id: "agustina-sussi",
                name: "Agustina Sussi",
                role: "GTE Zonal",
                phone: "11 2193 9543",
                email: "agustina.sussi@saboresexpress.com.ar",
                locales: ["Lomas del Mirador", "San Justo 1", "San Justo 2", "San Justo 3"],
              },
            ],
          },
        ],
      },
    },
  ],
};
